### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Nictrasavios** [ssblur/Just-What-I-Needed-Mod#7]
---- Minecraft Crash Report ----
// Don't do that.

Time: 22/03/16 12:38 AM
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at com.reimaginedgaming.blur.jwin.events.GUIHandlers.tickEvent(GUIHandlers.java:14)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_GUIHandlers_tickEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:127)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1395)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1072)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at net.minecraft.pathfinding.PathNavigate.<init>(SourceFile:58)
	at net.minecraft.pathfinding.PathNavigateGround.<init>(SourceFile:23)
	at net.minecraft.entity.EntityLiving.func_175447_b(EntityLiving.java:123)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:92)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:18)
	at net.minecraft.entity.EntityAgeable.<init>(SourceFile:30)
	at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:28)
	at net.minecraft.entity.passive.EntityPig.<init>(SourceFile:52)
	at com.reimaginedgaming.blur.jwin.client.SpawnOverlayRenderer.<clinit>(SpawnOverlayRenderer.java:25)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.reimaginedgaming.blur.jwin.events.GUIHandlers.tickEvent(GUIHandlers.java:14)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_GUIHandlers_tickEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:127)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1395)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['NictraSavios'/5917291, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,253,0), Chunk: (at 0,15,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['NictraSavios'/5917291, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2016894096 bytes (1923 MB) / 2365038592 bytes (2255 MB) up to 8375238656 bytes (7987 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1780 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1780-1.9.jar) 
	UCHIJA	Forge{12.16.0.1780} [Minecraft Forge] (forge-1.9-12.16.0.1780-1.9.jar) 
	UCHIJA	jwin{univ_compat_filler} [Just What I Needed] (jwin-0.12.0_1.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 354.35' Renderer: 'GeForce GT 740M/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.0.1780-1.9
	LWJGL: 2.9.4
	OpenGL: GeForce GT 740M/PCIe/SSE2 GL version 4.5.0 NVIDIA 354.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: RageCraft Modified.zip, Nictra FixPack.zip, BrothersJohnsonUnshaders.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

**Comment by ssblur** [comment]
This has been fixed, and will be resolved in the next update.
